// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package app

import (
	"context"
	"github.com/einride/bigquery-importer-slack/internal/api/bigqueryapi"
	"github.com/einride/bigquery-importer-slack/internal/api/slackapi"
	"go.uber.org/zap"
)

// Injectors from wire.go:

func InitApp(ctx context.Context, logger *zap.Logger, config *Config) (*App, func(), error) {
	jobConfig := config.Job
	client, cleanup, err := InitBigQueryClient(ctx, config, logger)
	if err != nil {
		return nil, nil, err
	}
	jobClient := &bigqueryapi.JobClient{
		Config:         jobConfig,
		BigQueryClient: client,
		Logger:         logger,
	}
	secretmanagerClient, cleanup2, err := InitSecretManagerClient(ctx, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	slackClient, err := InitSlackClient(ctx, config, secretmanagerClient, logger)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	slackapiSlackClient := &slackapi.SlackClient{
		Client: slackClient,
		Logger: logger,
	}
	app := &App{
		BigQueryJobClient: jobClient,
		SlackClient:       slackapiSlackClient,
		Logger:            logger,
	}
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
